version: "2"

services:
    nginx:
        build:
            context: ./nginx
        ports:
            - "8080:80"
        links:
            - phpfpm

    phpfpm:
        build:
            context: .
        volumes:
            - ./composer.json:/usr/local/src/composer.json
            - ./composer.lock:/usr/local/src/composer.lock
            - ./behat.yml:/usr/local/src/behat.yml
            - ./phpunit.xml:/usr/local/src/phpunit.yml
            - ./src:/usr/local/src/src
            - ./tests:/usr/local/src/tests
            - ./web:/usr/local/src/web
